version: '3.7'

services:
  easyzap-server:
    image: setupautomatizado/easyzap-server:latest
    networks:
      - network_public
    environment:
      - EASYZAP_ADMIN_TOKEN=H4Zbhw72PBKdTIgS
      - DB_USER=easyzap
      - DB_PASSWORD=easyzap
      - DB_NAME=easyzap
      - DB_HOST=db
      - DB_PORT=5432
      - TZ=America/Sao_Paulo
      - WEBHOOK_FORMAT=json
      - SESSION_DEVICE_NAME=Easyzap
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: "1"
          memory: 512MB
      labels:
        - traefik.enable=true
        - traefik.http.routers.easyzap-server.rule=Host(`api.easyzap.app`)
        - traefik.http.routers.easyzap-server.entrypoints=websecure
        - traefik.http.routers.easyzap-server.priority=1
        - traefik.http.routers.easyzap-server.tls.certresolver=letsencryptresolver
        - traefik.http.routers.easyzap-server.service=easyzap-server
        - traefik.http.services.easyzap-server.loadbalancer.server.port=8080
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 10s

networks:
  network_public:
    name: network_public
    external: true
